-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_PlayerStats" (
    "sofifa_id" INTEGER NOT NULL,
    "year" INTEGER NOT NULL,
    "overall" INTEGER,
    "potential" INTEGER,
    "value_eur" REAL,
    "wage_eur" REAL,
    "age" INTEGER,
    "dob" TEXT,
    "height_cm" INTEGER,
    "weight_kg" INTEGER,
    "club_name" INTEGER,
    "preferred_foot" TEXT,
    "weak_foot" INTEGER,
    "skill_moves" INTEGER,
    "international_reputation" INTEGER,
    "work_rate" TEXT,
    "body_type" TEXT,
    "real_face" TEXT,
    "pace" INTEGER,
    "shooting" INTEGER,
    "passing" INTEGER,
    "dribbling" INTEGER,
    "defending" INTEGER,
    "physic" INTEGER,
    "attacking_crossing" INTEGER,
    "attacking_finishing" INTEGER,
    "attacking_heading_accuracy" INTEGER,
    "attacking_short_passing" INTEGER,
    "attacking_volleys" INTEGER,
    "skill_dribbling" INTEGER,
    "skill_curve" INTEGER,
    "skill_fk_accuracy" INTEGER,
    "skill_long_passing" INTEGER,
    "skill_ball_control" INTEGER,
    "movement_acceleration" INTEGER,
    "movement_sprint_speed" INTEGER,
    "movement_agility" INTEGER,
    "movement_reactions" INTEGER,
    "movement_balance" INTEGER,
    "power_shot_power" INTEGER,
    "power_jumping" INTEGER,
    "power_stamina" INTEGER,
    "power_strength" INTEGER,
    "power_long_shots" INTEGER,
    "mentality_aggression" INTEGER,
    "mentality_interceptions" INTEGER,
    "mentality_positioning" INTEGER,
    "mentality_vision" INTEGER,
    "mentality_penalties" INTEGER,
    "mentality_composure" INTEGER,
    "defending_marking_awareness" INTEGER,
    "defending_standing_tackle" INTEGER,
    "defending_sliding_tackle" INTEGER,
    "goalkeeping_diving" INTEGER,
    "goalkeeping_handling" INTEGER,
    "goalkeeping_kicking" INTEGER,
    "goalkeeping_positioning" INTEGER,
    "goalkeeping_reflexes" INTEGER,
    "goalkeeping_speed" INTEGER,
    "ls" TEXT,
    "st" TEXT,
    "rs" TEXT,
    "lw" TEXT,
    "lf" TEXT,
    "cf" TEXT,
    "rf" TEXT,
    "rw" TEXT,
    "lam" TEXT,
    "cam" TEXT,
    "ram" TEXT,
    "lm" TEXT,
    "lcm" TEXT,
    "cm" TEXT,
    "rcm" TEXT,
    "rm" TEXT,
    "lwb" TEXT,
    "ldm" TEXT,
    "cdm" TEXT,
    "rdm" TEXT,
    "rwb" TEXT,
    "lb" TEXT,
    "lcb" TEXT,
    "cb" TEXT,
    "rcb" TEXT,
    "rb" TEXT,
    "gk" TEXT,
    "player_face_url" TEXT,

    PRIMARY KEY ("sofifa_id", "year"),
    CONSTRAINT "PlayerStats_sofifa_id_fkey" FOREIGN KEY ("sofifa_id") REFERENCES "Player" ("sofifa_id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_PlayerStats" ("age", "attacking_crossing", "attacking_finishing", "attacking_heading_accuracy", "attacking_short_passing", "attacking_volleys", "body_type", "cam", "cb", "cdm", "cf", "club_name", "cm", "defending", "defending_marking_awareness", "defending_sliding_tackle", "defending_standing_tackle", "dob", "dribbling", "gk", "goalkeeping_diving", "goalkeeping_handling", "goalkeeping_kicking", "goalkeeping_positioning", "goalkeeping_reflexes", "goalkeeping_speed", "height_cm", "international_reputation", "lam", "lb", "lcb", "lcm", "ldm", "lf", "lm", "ls", "lw", "lwb", "mentality_aggression", "mentality_composure", "mentality_interceptions", "mentality_penalties", "mentality_positioning", "mentality_vision", "movement_acceleration", "movement_agility", "movement_balance", "movement_reactions", "movement_sprint_speed", "overall", "pace", "passing", "physic", "player_face_url", "potential", "power_jumping", "power_long_shots", "power_shot_power", "power_stamina", "power_strength", "preferred_foot", "ram", "rb", "rcb", "rcm", "rdm", "real_face", "rf", "rm", "rs", "rw", "rwb", "shooting", "skill_ball_control", "skill_curve", "skill_dribbling", "skill_fk_accuracy", "skill_long_passing", "skill_moves", "sofifa_id", "st", "value_eur", "wage_eur", "weak_foot", "weight_kg", "work_rate", "year") SELECT "age", "attacking_crossing", "attacking_finishing", "attacking_heading_accuracy", "attacking_short_passing", "attacking_volleys", "body_type", "cam", "cb", "cdm", "cf", "club_name", "cm", "defending", "defending_marking_awareness", "defending_sliding_tackle", "defending_standing_tackle", "dob", "dribbling", "gk", "goalkeeping_diving", "goalkeeping_handling", "goalkeeping_kicking", "goalkeeping_positioning", "goalkeeping_reflexes", "goalkeeping_speed", "height_cm", "international_reputation", "lam", "lb", "lcb", "lcm", "ldm", "lf", "lm", "ls", "lw", "lwb", "mentality_aggression", "mentality_composure", "mentality_interceptions", "mentality_penalties", "mentality_positioning", "mentality_vision", "movement_acceleration", "movement_agility", "movement_balance", "movement_reactions", "movement_sprint_speed", "overall", "pace", "passing", "physic", "player_face_url", "potential", "power_jumping", "power_long_shots", "power_shot_power", "power_stamina", "power_strength", "preferred_foot", "ram", "rb", "rcb", "rcm", "rdm", "real_face", "rf", "rm", "rs", "rw", "rwb", "shooting", "skill_ball_control", "skill_curve", "skill_dribbling", "skill_fk_accuracy", "skill_long_passing", "skill_moves", "sofifa_id", "st", "value_eur", "wage_eur", "weak_foot", "weight_kg", "work_rate", "year" FROM "PlayerStats";
DROP TABLE "PlayerStats";
ALTER TABLE "new_PlayerStats" RENAME TO "PlayerStats";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
