nations_array = [
    {'nationality_id': 48, 'nationality_name': 'Turkey', 'nation_flag_url': 'https://cdn.sofifa.net/flags/tr.png'}, 
    {'nationality_id': 20, 'nationality_name': 'Georgia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ge.png'}, 
    {'nationality_id': 101, 'nationality_name': 'Burkina Faso', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bf.png'}, 
    {'nationality_id': 9, 'nationality_name': 'Bulgaria', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bg.png'}, 
    {'nationality_id': 189, 'nationality_name': 'Turkmenistan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/tm.png'}, 
    {'nationality_id': 81, 'nationality_name': 'Honduras', 'nation_flag_url': 'https://cdn.sofifa.net/flags/hn.png'}, 
    {'nationality_id': 13, 'nationality_name': 'Denmark', 'nation_flag_url': 'https://cdn.sofifa.net/flags/dk.png'}, 
    {'nationality_id': 85, 'nationality_name': 'Curacao', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cw.png'}, 
    {'nationality_id': 104, 'nationality_name': 'Cape Verde Islands', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cv.png'}, 
    {'nationality_id': 127, 'nationality_name': 'Mauritania', 'nation_flag_url': 'https://cdn.sofifa.net/flags/mr.png'}, 
    {'nationality_id': 133, 'nationality_name': 'Nigeria', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ng.png'}, 
    {'nationality_id': 160, 'nationality_name': 'Indonesia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/id.png'}, 
    {'nationality_id': 208, 'nationality_name': 'Estonia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ee.png'}, 
    {'nationality_id': 214, 'nationality_name': 'Comoros', 'nation_flag_url': 'https://cdn.sofifa.net/flags/km.png'}, 
    {'nationality_id': 191, 'nationality_name': 'Uzbekistan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/uz.png'}, 
    {'nationality_id': 198, 'nationality_name': 'New Zealand', 'nation_flag_url': 'https://cdn.sofifa.net/flags/nz.png'}, 
    {'nationality_id': 78, 'nationality_name': 'Guatemala', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gt.png'}, 
    {'nationality_id': 26, 'nationality_name': 'Israel', 'nation_flag_url': 'https://cdn.sofifa.net/flags/il.png'}, 
    {'nationality_id': 164, 'nationality_name': 'Jordan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/jo.png'}, 
    {'nationality_id': 17, 'nationality_name': 'Finland', 'nation_flag_url': 'https://cdn.sofifa.net/flags/fi.png'}, 
    {'nationality_id': 195, 'nationality_name': 'Australia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/au.png'}, 
    {'nationality_id': 6, 'nationality_name': 'Belarus', 'nation_flag_url': 'https://cdn.sofifa.net/flags/by.png'}, 
    {'nationality_id': 35, 'nationality_name': 'Northern Ireland', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gb-nir.png'}, 
    {'nationality_id': 10, 'nationality_name': 'Croatia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/hr.png'}, 
    {'nationality_id': 107, 'nationality_name': 'Congo', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cg.png'}, 
    {'nationality_id': 140, 'nationality_name': 'South Africa', 'nation_flag_url': 'https://cdn.sofifa.net/flags/za.png'}, 
    {'nationality_id': 97, 'nationality_name': 'Algeria', 'nation_flag_url': 'https://cdn.sofifa.net/flags/dz.png'}, 
    {'nationality_id': 54, 'nationality_name': 'Brazil', 'nation_flag_url': 'https://cdn.sofifa.net/flags/br.png'}, 
    {'nationality_id': 95, 'nationality_name': 'United States', 'nation_flag_url': 'https://cdn.sofifa.net/flags/us.png'}, 
    {'nationality_id': 51, 'nationality_name': 'Serbia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/rs.png'}, 
    {'nationality_id': 129, 'nationality_name': 'Morocco', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ma.png'}, 
    {'nationality_id': 45, 'nationality_name': 'Spain', 'nation_flag_url': 'https://cdn.sofifa.net/flags/es.png'}, 
    {'nationality_id': 115, 'nationality_name': 'Gabon', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ga.png'}, 
    {'nationality_id': 168, 'nationality_name': 'Kuwait', 'nation_flag_url': 'https://cdn.sofifa.net/flags/kw.png'}, 
    {'nationality_id': 90, 'nationality_name': 'Saint Lucia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/lc.png'}, 
    {'nationality_id': 89, 'nationality_name': 'Saint Kitts and Nevis', 'nation_flag_url': 'https://cdn.sofifa.net/flags/kn.png'}, 
    {'nationality_id': 171, 'nationality_name': 'Lebanon', 'nation_flag_url': 'https://cdn.sofifa.net/flags/lb.png'}, 
    {'nationality_id': 155, 'nationality_name': 'China PR', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cn.png'}, 
    {'nationality_id': 4, 'nationality_name': 'Austria', 'nation_flag_url': 'https://cdn.sofifa.net/flags/at.png'}, 
    {'nationality_id': 24, 'nationality_name': 'Iceland', 'nation_flag_url': 'https://cdn.sofifa.net/flags/is.png'}, 
    {'nationality_id': 27, 'nationality_name': 'Italy', 'nation_flag_url': 'https://cdn.sofifa.net/flags/it.png'}, 
    {'nationality_id': 32, 'nationality_name': 'Malta', 'nation_flag_url': 'https://cdn.sofifa.net/flags/mt.png'}, 
    {'nationality_id': 166, 'nationality_name': 'Korea DPR', 'nation_flag_url': 'https://cdn.sofifa.net/flags/kp.png'}, 
    {'nationality_id': 61, 'nationality_name': 'Venezuela', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ve.png'}, 
    {'nationality_id': 112, 'nationality_name': 'Equatorial Guinea', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gq.png'}, 
    {'nationality_id': 37, 'nationality_name': 'Poland', 'nation_flag_url': 'https://cdn.sofifa.net/flags/pl.png'}, 
    {'nationality_id': 8, 'nationality_name': 'Bosnia and Herzegovina', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ba.png'}, 
    {'nationality_id': 144, 'nationality_name': 'Togo', 'nation_flag_url': 'https://cdn.sofifa.net/flags/tg.png'}, 
    {'nationality_id': 79, 'nationality_name': 'Guyana', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gy.png'}, 
    {'nationality_id': 60, 'nationality_name': 'Uruguay', 'nation_flag_url': 'https://cdn.sofifa.net/flags/uy.png'}, 
    {'nationality_id': 188, 'nationality_name': 'Thailand', 'nation_flag_url': 'https://cdn.sofifa.net/flags/th.png'}, 
    {'nationality_id': 84, 'nationality_name': 'Montserrat', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ms.png'}, 
    {'nationality_id': 116, 'nationality_name': 'Gambia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gm.png'}, 
    {'nationality_id': 130, 'nationality_name': 'Mozambique', 'nation_flag_url': 'https://cdn.sofifa.net/flags/mz.png'}, 
    {'nationality_id': 15, 'nationality_name': 'Montenegro', 'nation_flag_url': 'https://cdn.sofifa.net/flags/me.png'}, 
    {'nationality_id': 118, 'nationality_name': 'Guinea', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gn.png'}, 
    {'nationality_id': 117, 'nationality_name': 'Ghana', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gh.png'}, 
    {'nationality_id': 154, 'nationality_name': 'Cambodia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/kh.png'}, 
    {'nationality_id': 29, 'nationality_name': 'Liechtenstein', 'nation_flag_url': 'https://cdn.sofifa.net/flags/li.png'}, 
    {'nationality_id': 70, 'nationality_name': 'Canada', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ca.png'}, 
    {'nationality_id': 148, 'nationality_name': 'Zimbabwe', 'nation_flag_url': 'https://cdn.sofifa.net/flags/zw.png'}, 
    {'nationality_id': 59, 'nationality_name': 'Peru', 'nation_flag_url': 'https://cdn.sofifa.net/flags/pe.png'}, 
    {'nationality_id': 39, 'nationality_name': 'Romania', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ro.png'}, 
    {'nationality_id': 120, 'nationality_name': 'Kenya', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ke.png'}, 
    {'nationality_id': 50, 'nationality_name': 'Wales', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gb-wls.png'}, 
    {'nationality_id': 31, 'nationality_name': 'Luxembourg', 'nation_flag_url': 'https://cdn.sofifa.net/flags/lu.png'}, 
    {'nationality_id': 103, 'nationality_name': 'Cameroon', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cm.png'}, 
    {'nationality_id': 150, 'nationality_name': 'Bahrain', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bh.png'}, 
    {'nationality_id': 215, 'nationality_name': 'New Caledonia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/nc.png'}, 
    {'nationality_id': 34, 'nationality_name': 'Netherlands', 'nation_flag_url': 'https://cdn.sofifa.net/flags/nl.png'}, 
    {'nationality_id': 197, 'nationality_name': 'Fiji', 'nation_flag_url': 'https://cdn.sofifa.net/flags/fj.png'}, 
    {'nationality_id': 132, 'nationality_name': 'Niger', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ne.png'}, 
    {'nationality_id': 11, 'nationality_name': 'Cyprus', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cy.png'}, 
    {'nationality_id': 25, 'nationality_name': 'Republic of Ireland', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ie.png'}, 
    {'nationality_id': 108, 'nationality_name': "C�te d'Ivoire", 'nation_flag_url': 'https://cdn.sofifa.net/flags/ci.png'}, 
    {'nationality_id': 77, 'nationality_name': 'Grenada', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gd.png'}, 
    {'nationality_id': 165, 'nationality_name': 'Kazakhstan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/kz.png'}, 
    {'nationality_id': 219, 'nationality_name': 'Kosovo', 'nation_flag_url': 'https://cdn.sofifa.net/flags/xk.png'}, 
    {'nationality_id': 205, 'nationality_name': 'Gibraltar', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gi.png'}, 
    {'nationality_id': 72, 'nationality_name': 'Costa Rica', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cr.png'}, 
    {'nationality_id': 136, 'nationality_name': 'Senegal', 'nation_flag_url': 'https://cdn.sofifa.net/flags/sn.png'}, 
    {'nationality_id': 138, 'nationality_name': 'Sierra Leone', 'nation_flag_url': 'https://cdn.sofifa.net/flags/sl.png'}, 
    {'nationality_id': 159, 'nationality_name': 'India', 'nation_flag_url': 'https://cdn.sofifa.net/flags/in.png'}, 
    {'nationality_id': 68, 'nationality_name': 'Bermuda', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bm.png'}, 
    {'nationality_id': 40, 'nationality_name': 'Russia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ru.png'}, 
    {'nationality_id': 53, 'nationality_name': 'Bolivia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bo.png'}, 
    {'nationality_id': 123, 'nationality_name': 'Libya', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ly.png'}, 
    {'nationality_id': 63, 'nationality_name': 'Antigua and Barbuda', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ag.png'}, 
    {'nationality_id': 161, 'nationality_name': 'Iran', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ir.png'}, 
    {'nationality_id': 147, 'nationality_name': 'Zambia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/zm.png'}, 
    {'nationality_id': 73, 'nationality_name': 'Cuba', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cu.png'}, 
    {'nationality_id': 56, 'nationality_name': 'Colombia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/co.png'}, 
    {'nationality_id': 16, 'nationality_name': 'Faroe Islands', 'nation_flag_url': 'https://cdn.sofifa.net/flags/fo.png'}, 
    {'nationality_id': 92, 'nationality_name': 'Suriname', 'nation_flag_url': 'https://cdn.sofifa.net/flags/sr.png'}, 
    {'nationality_id': 162, 'nationality_name': 'Iraq', 'nation_flag_url': 'https://cdn.sofifa.net/flags/iq.png'}, 
    {'nationality_id': 102, 'nationality_name': 'Burundi', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bi.png'}, 
    {'nationality_id': 43, 'nationality_name': 'Slovakia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/sk.png'}, 
    {'nationality_id': 3, 'nationality_name': 'Armenia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/am.png'}, 
    {'nationality_id': 146, 'nationality_name': 'Uganda', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ug.png'}, 
    {'nationality_id': 44, 'nationality_name': 'Slovenia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/si.png'}, 
    {'nationality_id': 111, 'nationality_name': 'Egypt', 'nation_flag_url': 'https://cdn.sofifa.net/flags/eg.png'}, 
    {'nationality_id': 66, 'nationality_name': 'Barbados', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bb.png'}, 
    {'nationality_id': 7, 'nationality_name': 'Belgium', 'nation_flag_url': 'https://cdn.sofifa.net/flags/be.png'}, 
    {'nationality_id': 183, 'nationality_name': 'Saudi Arabia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/sa.png'}, 
    {'nationality_id': 87, 'nationality_name': 'Panama', 'nation_flag_url': 'https://cdn.sofifa.net/flags/pa.png'}, 
    {'nationality_id': 181, 'nationality_name': 'Philippines', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ph.png'}, 
    {'nationality_id': 186, 'nationality_name': 'Syria', 'nation_flag_url': 'https://cdn.sofifa.net/flags/sy.png'}, 
    {'nationality_id': 124, 'nationality_name': 'Madagascar', 'nation_flag_url': 'https://cdn.sofifa.net/flags/mg.png'}, 
    {'nationality_id': 126, 'nationality_name': 'Mali', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ml.png'}, 
    {'nationality_id': 18, 'nationality_name': 'France', 'nation_flag_url': 'https://cdn.sofifa.net/flags/fr.png'}, 
    {'nationality_id': 14, 'nationality_name': 'England', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gb-eng.png'}, 
    {'nationality_id': 58, 'nationality_name': 'Paraguay', 'nation_flag_url': 'https://cdn.sofifa.net/flags/py.png'}, 
    {'nationality_id': 169, 'nationality_name': 'Kyrgyzstan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/kg.png'}, 
    {'nationality_id': 47, 'nationality_name': 'Switzerland', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ch.png'}, 
    {'nationality_id': 167, 'nationality_name': 'Korea Republic', 'nation_flag_url': 'https://cdn.sofifa.net/flags/kr.png'}, 
    {'nationality_id': 36, 'nationality_name': 'Norway', 'nation_flag_url': 'https://cdn.sofifa.net/flags/no.png'}, 
    {'nationality_id': 57, 'nationality_name': 'Ecuador', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ec.png'}, 
    {'nationality_id': 55, 'nationality_name': 'Chile', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cl.png'}, 
    {'nationality_id': 12, 'nationality_name': 'Czech Republic', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cz.png'}, 
    {'nationality_id': 23, 'nationality_name': 'Hungary', 'nation_flag_url': 'https://cdn.sofifa.net/flags/hu.png'}, 
    {'nationality_id': 80, 'nationality_name': 'Haiti', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ht.png'}, 
    {'nationality_id': 83, 'nationality_name': 'Mexico', 'nation_flag_url': 'https://cdn.sofifa.net/flags/mx.png'}, 
    {'nationality_id': 42, 'nationality_name': 'Scotland', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gb-sct.png'}, 
    {'nationality_id': 38, 'nationality_name': 'Portugal', 'nation_flag_url': 'https://cdn.sofifa.net/flags/pt.png'}, 
    {'nationality_id': 30, 'nationality_name': 'Lithuania', 'nation_flag_url': 'https://cdn.sofifa.net/flags/lt.png'}, 
    {'nationality_id': 82, 'nationality_name': 'Jamaica', 'nation_flag_url': 'https://cdn.sofifa.net/flags/jm.png'}, 
    {'nationality_id': 110, 'nationality_name': 'Congo DR', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cd.png'}, 
    {'nationality_id': 99, 'nationality_name': 'Benin', 'nation_flag_url': 'https://cdn.sofifa.net/flags/bj.png'}, 
    {'nationality_id': 46, 'nationality_name': 'Sweden', 'nation_flag_url': 'https://cdn.sofifa.net/flags/se.png'}, 
    {'nationality_id': 22, 'nationality_name': 'Greece', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gr.png'}, 
    {'nationality_id': 28, 'nationality_name': 'Latvia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/lv.png'}, 
    {'nationality_id': 19, 'nationality_name': 'North Macedonia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/mk.png'}, 
    {'nationality_id': 5, 'nationality_name': 'Azerbaijan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/az.png'}, 
    {'nationality_id': 1, 'nationality_name': 'Albania', 'nation_flag_url': 'https://cdn.sofifa.net/flags/al.png'}, 
    {'nationality_id': 93, 'nationality_name': 'Trinidad and Tobago', 'nation_flag_url': 'https://cdn.sofifa.net/flags/tt.png'}, 
    {'nationality_id': 157, 'nationality_name': 'Guam', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gu.png'}, 
    {'nationality_id': 180, 'nationality_name': 'Palestine', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ps.png'}, 
    {'nationality_id': 178, 'nationality_name': 'Oman', 'nation_flag_url': 'https://cdn.sofifa.net/flags/om.png'}, 
    {'nationality_id': 98, 'nationality_name': 'Angola', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ao.png'}, 
    {'nationality_id': 122, 'nationality_name': 'Liberia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/lr.png'}, 
    {'nationality_id': 33, 'nationality_name': 'Moldova', 'nation_flag_url': 'https://cdn.sofifa.net/flags/md.png'}, 
    {'nationality_id': 145, 'nationality_name': 'Tunisia', 'nation_flag_url': 'https://cdn.sofifa.net/flags/tn.png'}, 
    {'nationality_id': 105, 'nationality_name': 'Central African Republic', 'nation_flag_url': 'https://cdn.sofifa.net/flags/cf.png'}, 
    {'nationality_id': 21, 'nationality_name': 'Germany', 'nation_flag_url': 'https://cdn.sofifa.net/flags/de.png'}, 
    {'nationality_id': 163, 'nationality_name': 'Japan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/jp.png'}, 
    {'nationality_id': 141, 'nationality_name': 'Sudan', 'nation_flag_url': 'https://cdn.sofifa.net/flags/sd.png'}, 
    {'nationality_id': 49, 'nationality_name': 'Ukraine', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ua.png'}, 
    {'nationality_id': 52, 'nationality_name': 'Argentina', 'nation_flag_url': 'https://cdn.sofifa.net/flags/ar.png'}, 
    {'nationality_id': 119, 'nationality_name': 'Guinea Bissau', 'nation_flag_url': 'https://cdn.sofifa.net/flags/gw.png'}
    ]